-- Transaction block generated by POSTGRESQL from ERDTOOLS


BEGIN;


CREATE TABLE IF NOT EXISTS public."User"
(
    user_id uuid NOT NULL,
    full_name character varying(100) NOT NULL,
    membership_date date NOT NULL,
    email_address character varying(100) NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public."Book"
(
    isbn character varying(13) NOT NULL,
    title text NOT NULL,
    author character varying(50) NOT NULL,
    quantity_available integer NOT NULL,
    published_year date NOT NULL,
    genre character varying(30) NOT NULL,
    PRIMARY KEY (isbn)
);

CREATE TABLE IF NOT EXISTS public."BookLoan"
(
    loan_date date NOT NULL,
    return_date date NOT NULL,
    status text NOT NULL,
    user_id uuid NOT NULL,
    book_isbn character varying(13) NOT NULL,
    CONSTRAINT user_book_id PRIMARY KEY (user_id, book_isbn)
);

ALTER TABLE IF EXISTS public."BookLoan"
    ADD CONSTRAINT book_isbn FOREIGN KEY (book_isbn)
    REFERENCES public."Book" (isbn) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."BookLoan"
    ADD CONSTRAINT user_id FOREIGN KEY (user_id)
    REFERENCES public."User" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;